image: docker:latest

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install pytest
    - pip install -r requirements.txt
    - python -m pytest ./main_test.py
    - docker build .

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - docker build -t anonalangford/rest_star_wars:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push anonalangford/rest_star_wars:latest
  only:
    - master

production:
  stage: deploy
  script:
    - apt-get update -qy
    - docker build -t anonalangford/rest_star_wars:$CI_COMMIT_TAG .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push anonalangford/rest_star_wars:$CI_COMMIT_TAG
  only:
    - tags