
image: "python:2.7" 

stages:
  - pylint
  - pytest
  - helm
  - build
  - deploy

pylint:
  stage: pylint
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install pylint
    - pip install -r requirements.txt
  script:
    - python -m pylint ./*.py
  only:
    - merge_requests
  
pytest:
  stage: pytest
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install pytest
    - pip install -r requirements.txt
  script:
    - python -m pytest ./main_test.py
  only:
    - merge_requests

helm:
  stage: helm
  before_script:
    - curl https://baltocdn.com/helm/signing.asc | apt-key add -
    - apt-get install apt-transport-https --yes
    - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
    - apt-get update -qy
    - apt-get install -y helm
  script:
    - helm lint ./rest-star-wars/
    - helm template ./rest-star-wars/
  only:
    - merge_requests

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker build .
  only:
    - merge_requests

production:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker build -t anonalangford/rest_star_wars:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push anonalangford/rest_star_wars:latest
  only:
    - master

tagging:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - docker build -t anonalangford/rest_star_wars:$CI_COMMIT_TAG .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push anonalangford/rest_star_wars:$CI_COMMIT_TAG
  only:
    - tags